name: rent360-production
services:
- name: rent360-app
  source_dir: /
  github:
    repo: your-username/rent360
    branch: main
    deploy_on_push: true
  run_command: npm start
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: professional-xs
  envs:
  - key: NODE_ENV
    value: production
  - key: NEXT_TELEMETRY_DISABLED
    value: "1"
  # Variables de entorno críticas para la aplicación
  # ✅ CONFIGURADO: Usando variable automática de DigitalOcean para base de datos
  - key: DATABASE_URL
    value: "${rent360-db.DATABASE_URL}"
  - key: JWT_SECRET
    value: "e9d813f4345645052a1cd1abe705b96c064f75f4f4e2313443293f618eec722f"
  - key: JWT_REFRESH_SECRET
    value: "63bfba64e744e820bee5da89ffeb95851ff1d7d2f696277bc5d76c4b6c238fb8"
  - key: NEXTAUTH_SECRET
    value: "178cc98439d47733e8a07ceea76c1d716bdde0e9d1b83d4600abc39c06c0e05e"
  # Digital Ocean App Platform establece PORT automáticamente (normalmente 8080)
  # No establecer PORT manualmente
  health_check:
    http_path: /api/health
    initial_delay_seconds: 120
    period_seconds: 10
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 5
  http_port: 8080
  internal_ports:
  - 8080

databases:
- name: rent360-db
  engine: PG
  version: "15"
  size: professional-xs
  num_nodes: 1

# Configuración de dominio personalizado
# domains:
# - domain: rent360.cl
#   type: PRIMARY
#   wildcard: true
#   zone: rent360.cl
