name: rent360-production
services:
- name: rent360-app
  source_dir: /
  github:
    repo: your-username/rent360
    branch: main
    deploy_on_push: true
  run_command: npm start
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: professional-xs
  envs:
  - key: NODE_ENV
    value: production
  - key: NEXT_TELEMETRY_DISABLED
    value: "1"
  # Variables de entorno críticas para la aplicación
  # ⚠️ REEMPLAZA con tu URL real de PostgreSQL
  - key: DATABASE_URL
    value: "postgresql://rent360_user:REPLACE_WITH_YOUR_DB_PASSWORD@REPLACE_WITH_YOUR_DB_HOST:25060/rent360_prod"
  - key: JWT_SECRET
    value: "REPLACE_WITH_YOUR_OWN_JWT_SECRET_MIN_32_CHARS"
  - key: JWT_REFRESH_SECRET
    value: "REPLACE_WITH_YOUR_OWN_JWT_REFRESH_SECRET_MIN_32_CHARS"
  - key: NEXTAUTH_SECRET
    value: "REPLACE_WITH_YOUR_OWN_NEXTAUTH_SECRET_MIN_32_CHARS"
  - key: PORT
    value: "3000"
  health_check:
    http_path: /api/health
  internal_ports:
  - 3000

databases:
- name: rent360-db
  engine: PG
  version: "15"
  size: professional-xs
  num_nodes: 1

# Configuración de dominio personalizado
# domains:
# - domain: rent360.cl
#   type: PRIMARY
#   wildcard: true
#   zone: rent360.cl
