// Tipos generados automáticamente desde Prisma
export type {
  User,
  Property,
  Contract,
  Payment,
  Review,
  Message,
  Ticket,
  TicketComment,
  Visit,
  Maintenance,
  Notification,
  SystemSetting,
  EmailTemplate,
  AuditLog,
  Document,
  BankAccount,
  MaintenanceProvider,
  ServiceProvider,
  ProviderDocuments,
  ServiceJob,
  ProviderTransaction,
  PlatformConfig,
  SystemLog,
  ContractSignature,
} from '@prisma/client';

// Re-export enums from main types file
export {
  UserRole,
  PropertyStatus,
  PropertyType,
  ContractStatus,
  PaymentStatus,
  PaymentMethod,
  MessageStatus,
  TicketPriority,
  TicketStatus,
  VisitStatus,
  MaintenancePriority,
  MaintenanceStatus,
  NotificationType,
  AccountType,
  ServiceType,
  ProviderStatus,
  ServiceJobStatus,
  ProviderType,
  TransactionStatus,
  SignatureStatus,
  RefundStatus,
} from '../types';
