# AWS CloudFront Distribution Configuration for Rent360
# This is a CloudFormation template for creating a CloudFront distribution
# Use with: aws cloudformation deploy --template-file cloudfront-distribution.yaml --stack-name rent360-cdn

AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFront distribution for Rent360 production environment'

Parameters:
  S3BucketName:
    Type: String
    Default: rent360-production-files
    Description: Name of the S3 bucket for static assets

  CertificateArn:
    Type: String
    Description: ARN of the ACM certificate for HTTPS

  DomainName:
    Type: String
    Default: rent360.cl
    Description: Primary domain name

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: Rent360 Production CDN
        Enabled: true
        HttpVersion: http2

        # Origins
        Origins:
          - DomainName: !Ref S3BucketName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}

          - DomainName: api.rent360.cl
            Id: APIOrigin
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2

        # Default cache behavior
        DefaultCacheBehavior:
          TargetOriginId: APIOrigin
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: whitelist
              WhitelistedNames:
                - session
                - auth_token

          # Cache settings for API responses
          CachePolicyId: !Ref APICachePolicy

        # Additional cache behaviors
        CacheBehaviors:
          # Static assets from S3
          - PathPattern: /_next/static/*
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
            CachePolicyId: !Ref StaticAssetsCachePolicy

          - PathPattern: /uploads/*
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
            CachePolicyId: !Ref UserUploadsCachePolicy

          - PathPattern: /images/*
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
            CachePolicyId: !Ref ImagesCachePolicy

        # Custom error pages
        CustomErrorResponses:
          - ErrorCode: 404
            ResponsePagePath: /404.html
            ResponseCode: 404
            ErrorCachingMinTTL: 300
          - ErrorCode: 500
            ResponsePagePath: /500.html
            ResponseCode: 500
            ErrorCachingMinTTL: 300

        # SSL/TLS settings
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

        # Price class (use PriceClass_100 for global coverage)
        PriceClass: PriceClass_100

        # Logging
        Logging:
          Bucket: !Sub ${S3BucketName}-logs.s3.amazonaws.com
          IncludeCookies: false
          Prefix: cloudfront/

  # Origin Access Identity for S3
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::OriginAccessIdentity
    Properties:
      OriginAccessIdentityConfig:
        Comment: !Sub Access identity for ${S3BucketName}

  # Cache Policies
  StaticAssetsCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: Rent360-StaticAssets
        Comment: Cache policy for static assets (_next/static/*)
        DefaultTTL: 31536000  # 1 year
        MaxTTL: 31536000
        MinTTL: 86400        # 1 day

        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

  UserUploadsCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: Rent360-UserUploads
        Comment: Cache policy for user uploaded files
        DefaultTTL: 86400   # 24 hours
        MaxTTL: 604800     # 1 week
        MinTTL: 3600       # 1 hour

        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

  ImagesCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: Rent360-Images
        Comment: Cache policy for images
        DefaultTTL: 86400   # 24 hours
        MaxTTL: 604800     # 1 week
        MinTTL: 3600       # 1 hour

        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

  APICachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: Rent360-API
        Comment: Cache policy for API responses
        DefaultTTL: 0       # No default caching
        MaxTTL: 300         # 5 minutes max
        MinTTL: 0           # No minimum

        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: whitelist
            Cookies:
              - session
              - auth_token
          HeadersConfig:
            HeaderBehavior: whitelist
            Headers:
              - Authorization
              - Accept-Language
          QueryStringsConfig:
            QueryStringBehavior: all

  # Response Headers Policy for security
  SecurityHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: Rent360-SecurityHeaders
        Comment: Security headers for Rent360

        SecurityHeadersConfig:
          # Content Security Policy
          ContentSecurityPolicy:
            ContentSecurityPolicy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://api.rent360.cl"

          # Strict Transport Security
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 31536000
            IncludeSubdomains: true
            Override: true

          # X-Frame-Options
          FrameOptions:
            FrameOption: DENY
            Override: true

          # X-Content-Type-Options
          ContentTypeOptions:
            Override: true

          # Referrer Policy
          ReferrerPolicy:
            ReferrerPolicy: strict-origin-when-cross-origin
            Override: true

        # CORS headers
        CorsConfig:
          AccessControlAllowCredentials: true
          AccessControlAllowHeaders:
            - '*'
          AccessControlAllowMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          AccessControlAllowOrigins:
            - https://rent360.cl
            - https://www.rent360.cl
          OriginOverride: true

Outputs:
  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution
    Export:
      Name: Rent360-CloudFront-Distribution-ID

  CloudFrontDomainName:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: Rent360-CloudFront-Domain-Name

  CloudFrontURL:
    Description: CloudFront Distribution URL
    Value: !Sub https://${CloudFrontDistribution.DomainName}
    Export:
      Name: Rent360-CloudFront-URL
